/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReplicasListResponseDataInner
 */
public class ReplicasListResponseDataInnerTest {
    private final ReplicasListResponseDataInner model = new ReplicasListResponseDataInner();

    /**
     * Model tests for ReplicasListResponseDataInner
     */
    @Test
    public void testReplicasListResponseDataInner() {
        // TODO: test ReplicasListResponseDataInner
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'replicaId'
     */
    @Test
    public void replicaIdTest() {
        // TODO: test replicaId
    }

    /**
     * Test the property 'replicaName'
     */
    @Test
    public void replicaNameTest() {
        // TODO: test replicaName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'thumbnailVideoUrl'
     */
    @Test
    public void thumbnailVideoUrlTest() {
        // TODO: test thumbnailVideoUrl
    }

    /**
     * Test the property 'trainingProgress'
     */
    @Test
    public void trainingProgressTest() {
        // TODO: test trainingProgress
    }

}
