/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideosGetAllResponseDataInner
 */
public class VideosGetAllResponseDataInnerTest {
    private final VideosGetAllResponseDataInner model = new VideosGetAllResponseDataInner();

    /**
     * Model tests for VideosGetAllResponseDataInner
     */
    @Test
    public void testVideosGetAllResponseDataInner() {
        // TODO: test VideosGetAllResponseDataInner
    }

    /**
     * Test the property 'backgroundSourceUrl'
     */
    @Test
    public void backgroundSourceUrlTest() {
        // TODO: test backgroundSourceUrl
    }

    /**
     * Test the property 'backgroundUrl'
     */
    @Test
    public void backgroundUrlTest() {
        // TODO: test backgroundUrl
    }

    /**
     * Test the property 'replicaId'
     */
    @Test
    public void replicaIdTest() {
        // TODO: test replicaId
    }

    /**
     * Test the property 'script'
     */
    @Test
    public void scriptTest() {
        // TODO: test script
    }

    /**
     * Test the property 'videoName'
     */
    @Test
    public void videoNameTest() {
        // TODO: test videoName
    }

}
