/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideosUpdateNameRequest
 */
public class VideosUpdateNameRequestTest {
    private final VideosUpdateNameRequest model = new VideosUpdateNameRequest();

    /**
     * Model tests for VideosUpdateNameRequest
     */
    @Test
    public void testVideosUpdateNameRequest() {
        // TODO: test VideosUpdateNameRequest
    }

    /**
     * Test the property 'videoName'
     */
    @Test
    public void videoNameTest() {
        // TODO: test videoName
    }

}
