/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VideosGetByVideoIdResponseData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VideosGetByVideoIdResponse
 */
public class VideosGetByVideoIdResponseTest {
    private final VideosGetByVideoIdResponse model = new VideosGetByVideoIdResponse();

    /**
     * Model tests for VideosGetByVideoIdResponse
     */
    @Test
    public void testVideosGetByVideoIdResponse() {
        // TODO: test VideosGetByVideoIdResponse
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'hostedUrl'
     */
    @Test
    public void hostedUrlTest() {
        // TODO: test hostedUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusDetails'
     */
    @Test
    public void statusDetailsTest() {
        // TODO: test statusDetails
    }

    /**
     * Test the property 'streamUrl'
     */
    @Test
    public void streamUrlTest() {
        // TODO: test streamUrl
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'videoId'
     */
    @Test
    public void videoIdTest() {
        // TODO: test videoId
    }

}
