/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReplicasGetReplicaByIdResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReplicasGetReplicaByIdResponse {
  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "error_message";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  private String errorMessage;

  public static final String SERIALIZED_NAME_REPLICA_ID = "replica_id";
  @SerializedName(SERIALIZED_NAME_REPLICA_ID)
  private String replicaId;

  public static final String SERIALIZED_NAME_REPLICA_NAME = "replica_name";
  @SerializedName(SERIALIZED_NAME_REPLICA_NAME)
  private String replicaName;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_THUMBNAIL_VIDEO_URL = "thumbnail_video_url";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL_VIDEO_URL)
  private String thumbnailVideoUrl;

  public static final String SERIALIZED_NAME_TRAINING_PROGRESS = "training_progress";
  @SerializedName(SERIALIZED_NAME_TRAINING_PROGRESS)
  private String trainingProgress;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public ReplicasGetReplicaByIdResponse() {
  }

  public ReplicasGetReplicaByIdResponse createdAt(String createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time the replica was created.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-01-24T07:14:03.327Z", value = "The date and time the replica was created.")

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public ReplicasGetReplicaByIdResponse errorMessage(String errorMessage) {
    
    
    
    
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * If the replica has an error, this will contain the error message.
   * @return errorMessage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If the replica has an error, this will contain the error message.")

  public String getErrorMessage() {
    return errorMessage;
  }


  public void setErrorMessage(String errorMessage) {
    
    
    
    this.errorMessage = errorMessage;
  }


  public ReplicasGetReplicaByIdResponse replicaId(String replicaId) {
    
    
    
    
    this.replicaId = replicaId;
    return this;
  }

   /**
   * A unique identifier for the replica.
   * @return replicaId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "r783537ef5", value = "A unique identifier for the replica.")

  public String getReplicaId() {
    return replicaId;
  }


  public void setReplicaId(String replicaId) {
    
    
    
    this.replicaId = replicaId;
  }


  public ReplicasGetReplicaByIdResponse replicaName(String replicaName) {
    
    
    
    
    this.replicaName = replicaName;
    return this;
  }

   /**
   * The name of the replica.
   * @return replicaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My Replica", value = "The name of the replica.")

  public String getReplicaName() {
    return replicaName;
  }


  public void setReplicaName(String replicaName) {
    
    
    
    this.replicaName = replicaName;
  }


  public ReplicasGetReplicaByIdResponse status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * The status of the replica.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "completed", value = "The status of the replica.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public ReplicasGetReplicaByIdResponse thumbnailVideoUrl(String thumbnailVideoUrl) {
    
    
    
    
    this.thumbnailVideoUrl = thumbnailVideoUrl;
    return this;
  }

   /**
   * A direct link to the video that will be used as the thumbnail for the replica.
   * @return thumbnailVideoUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A direct link to the video that will be used as the thumbnail for the replica.")

  public String getThumbnailVideoUrl() {
    return thumbnailVideoUrl;
  }


  public void setThumbnailVideoUrl(String thumbnailVideoUrl) {
    
    
    
    this.thumbnailVideoUrl = thumbnailVideoUrl;
  }


  public ReplicasGetReplicaByIdResponse trainingProgress(String trainingProgress) {
    
    
    
    
    this.trainingProgress = trainingProgress;
    return this;
  }

   /**
   * The progress of the replica training.
   * @return trainingProgress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "100/100", value = "The progress of the replica training.")

  public String getTrainingProgress() {
    return trainingProgress;
  }


  public void setTrainingProgress(String trainingProgress) {
    
    
    
    this.trainingProgress = trainingProgress;
  }


  public ReplicasGetReplicaByIdResponse updatedAt(String updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * The date and time of when the replica was last updated.
   * @return updatedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-01-24T07:14:03.327Z", value = "The date and time of when the replica was last updated.")

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReplicasGetReplicaByIdResponse instance itself
   */
  public ReplicasGetReplicaByIdResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicasGetReplicaByIdResponse replicasGetReplicaByIdResponse = (ReplicasGetReplicaByIdResponse) o;
    return Objects.equals(this.createdAt, replicasGetReplicaByIdResponse.createdAt) &&
        Objects.equals(this.errorMessage, replicasGetReplicaByIdResponse.errorMessage) &&
        Objects.equals(this.replicaId, replicasGetReplicaByIdResponse.replicaId) &&
        Objects.equals(this.replicaName, replicasGetReplicaByIdResponse.replicaName) &&
        Objects.equals(this.status, replicasGetReplicaByIdResponse.status) &&
        Objects.equals(this.thumbnailVideoUrl, replicasGetReplicaByIdResponse.thumbnailVideoUrl) &&
        Objects.equals(this.trainingProgress, replicasGetReplicaByIdResponse.trainingProgress) &&
        Objects.equals(this.updatedAt, replicasGetReplicaByIdResponse.updatedAt)&&
        Objects.equals(this.additionalProperties, replicasGetReplicaByIdResponse.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, errorMessage, replicaId, replicaName, status, thumbnailVideoUrl, trainingProgress, updatedAt, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicasGetReplicaByIdResponse {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    replicaId: ").append(toIndentedString(replicaId)).append("\n");
    sb.append("    replicaName: ").append(toIndentedString(replicaName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    thumbnailVideoUrl: ").append(toIndentedString(thumbnailVideoUrl)).append("\n");
    sb.append("    trainingProgress: ").append(toIndentedString(trainingProgress)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("created_at");
    openapiFields.add("error_message");
    openapiFields.add("replica_id");
    openapiFields.add("replica_name");
    openapiFields.add("status");
    openapiFields.add("thumbnail_video_url");
    openapiFields.add("training_progress");
    openapiFields.add("updated_at");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReplicasGetReplicaByIdResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReplicasGetReplicaByIdResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplicasGetReplicaByIdResponse is not found in the empty JSON string", ReplicasGetReplicaByIdResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if (!jsonObj.get("error_message").isJsonNull() && (jsonObj.get("error_message") != null && !jsonObj.get("error_message").isJsonNull()) && !jsonObj.get("error_message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `error_message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("error_message").toString()));
      }
      if ((jsonObj.get("replica_id") != null && !jsonObj.get("replica_id").isJsonNull()) && !jsonObj.get("replica_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `replica_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replica_id").toString()));
      }
      if ((jsonObj.get("replica_name") != null && !jsonObj.get("replica_name").isJsonNull()) && !jsonObj.get("replica_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `replica_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replica_name").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("thumbnail_video_url") != null && !jsonObj.get("thumbnail_video_url").isJsonNull()) && !jsonObj.get("thumbnail_video_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thumbnail_video_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thumbnail_video_url").toString()));
      }
      if ((jsonObj.get("training_progress") != null && !jsonObj.get("training_progress").isJsonNull()) && !jsonObj.get("training_progress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `training_progress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("training_progress").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplicasGetReplicaByIdResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplicasGetReplicaByIdResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplicasGetReplicaByIdResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplicasGetReplicaByIdResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplicasGetReplicaByIdResponse>() {
           @Override
           public void write(JsonWriter out, ReplicasGetReplicaByIdResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplicasGetReplicaByIdResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReplicasGetReplicaByIdResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReplicasGetReplicaByIdResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReplicasGetReplicaByIdResponse
  * @throws IOException if the JSON string is invalid with respect to ReplicasGetReplicaByIdResponse
  */
  public static ReplicasGetReplicaByIdResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplicasGetReplicaByIdResponse.class);
  }

 /**
  * Convert an instance of ReplicasGetReplicaByIdResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

