/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ReplicasCreateNewReplicaRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ReplicasCreateNewReplicaRequest {
  public static final String SERIALIZED_NAME_CALLBACK_URL = "callback_url";
  @SerializedName(SERIALIZED_NAME_CALLBACK_URL)
  private String callbackUrl;

  public static final String SERIALIZED_NAME_REPLICA_NAME = "replica_name";
  @SerializedName(SERIALIZED_NAME_REPLICA_NAME)
  private String replicaName;

  public static final String SERIALIZED_NAME_TRAIN_VIDEO_URL = "train_video_url";
  @SerializedName(SERIALIZED_NAME_TRAIN_VIDEO_URL)
  private String trainVideoUrl;

  public ReplicasCreateNewReplicaRequest() {
  }

  public ReplicasCreateNewReplicaRequest callbackUrl(String callbackUrl) {
    
    
    
    
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * A url that will receive a callback on completion of replica training or on error.
   * @return callbackUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A url that will receive a callback on completion of replica training or on error.")

  public String getCallbackUrl() {
    return callbackUrl;
  }


  public void setCallbackUrl(String callbackUrl) {
    
    
    
    this.callbackUrl = callbackUrl;
  }


  public ReplicasCreateNewReplicaRequest replicaName(String replicaName) {
    
    
    
    
    this.replicaName = replicaName;
    return this;
  }

   /**
   * A name for the replica.
   * @return replicaName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A name for the replica.")

  public String getReplicaName() {
    return replicaName;
  }


  public void setReplicaName(String replicaName) {
    
    
    
    this.replicaName = replicaName;
  }


  public ReplicasCreateNewReplicaRequest trainVideoUrl(String trainVideoUrl) {
    
    
    
    
    this.trainVideoUrl = trainVideoUrl;
    return this;
  }

   /**
   * A direct link to a publicly accessible storage location such as an S3 bucket. This video will be used for replica training.
   * @return trainVideoUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A direct link to a publicly accessible storage location such as an S3 bucket. This video will be used for replica training.")

  public String getTrainVideoUrl() {
    return trainVideoUrl;
  }


  public void setTrainVideoUrl(String trainVideoUrl) {
    
    
    
    this.trainVideoUrl = trainVideoUrl;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReplicasCreateNewReplicaRequest instance itself
   */
  public ReplicasCreateNewReplicaRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicasCreateNewReplicaRequest replicasCreateNewReplicaRequest = (ReplicasCreateNewReplicaRequest) o;
    return Objects.equals(this.callbackUrl, replicasCreateNewReplicaRequest.callbackUrl) &&
        Objects.equals(this.replicaName, replicasCreateNewReplicaRequest.replicaName) &&
        Objects.equals(this.trainVideoUrl, replicasCreateNewReplicaRequest.trainVideoUrl)&&
        Objects.equals(this.additionalProperties, replicasCreateNewReplicaRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callbackUrl, replicaName, trainVideoUrl, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicasCreateNewReplicaRequest {\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    replicaName: ").append(toIndentedString(replicaName)).append("\n");
    sb.append("    trainVideoUrl: ").append(toIndentedString(trainVideoUrl)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("callback_url");
    openapiFields.add("replica_name");
    openapiFields.add("train_video_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("train_video_url");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReplicasCreateNewReplicaRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ReplicasCreateNewReplicaRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReplicasCreateNewReplicaRequest is not found in the empty JSON string", ReplicasCreateNewReplicaRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReplicasCreateNewReplicaRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("callback_url") != null && !jsonObj.get("callback_url").isJsonNull()) && !jsonObj.get("callback_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `callback_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("callback_url").toString()));
      }
      if ((jsonObj.get("replica_name") != null && !jsonObj.get("replica_name").isJsonNull()) && !jsonObj.get("replica_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `replica_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replica_name").toString()));
      }
      if (!jsonObj.get("train_video_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `train_video_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("train_video_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReplicasCreateNewReplicaRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReplicasCreateNewReplicaRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReplicasCreateNewReplicaRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReplicasCreateNewReplicaRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ReplicasCreateNewReplicaRequest>() {
           @Override
           public void write(JsonWriter out, ReplicasCreateNewReplicaRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReplicasCreateNewReplicaRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ReplicasCreateNewReplicaRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReplicasCreateNewReplicaRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReplicasCreateNewReplicaRequest
  * @throws IOException if the JSON string is invalid with respect to ReplicasCreateNewReplicaRequest
  */
  public static ReplicasCreateNewReplicaRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReplicasCreateNewReplicaRequest.class);
  }

 /**
  * Convert an instance of ReplicasCreateNewReplicaRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

