/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * VideosCreateVideoFromReplicaAndScriptRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class VideosCreateVideoFromReplicaAndScriptRequest {
  public static final String SERIALIZED_NAME_BACKGROUND_SOURCE_URL = "background_source_url";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_SOURCE_URL)
  private String backgroundSourceUrl;

  public static final String SERIALIZED_NAME_BACKGROUND_URL = "background_url";
  @SerializedName(SERIALIZED_NAME_BACKGROUND_URL)
  private String backgroundUrl;

  public static final String SERIALIZED_NAME_REPLICA_ID = "replica_id";
  @SerializedName(SERIALIZED_NAME_REPLICA_ID)
  private String replicaId;

  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  private String script;

  public static final String SERIALIZED_NAME_VIDEO_NAME = "video_name";
  @SerializedName(SERIALIZED_NAME_VIDEO_NAME)
  private String videoName;

  public VideosCreateVideoFromReplicaAndScriptRequest() {
  }

  public VideosCreateVideoFromReplicaAndScriptRequest backgroundSourceUrl(String backgroundSourceUrl) {
    
    
    
    
    this.backgroundSourceUrl = backgroundSourceUrl;
    return this;
  }

   /**
   * A direct link to a video that is publicly accessible via a storage location such as an S3 bucket. This will be used as the background for the video. The video must be publicly accessible.
   * @return backgroundSourceUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A direct link to a video that is publicly accessible via a storage location such as an S3 bucket. This will be used as the background for the video. The video must be publicly accessible.")

  public String getBackgroundSourceUrl() {
    return backgroundSourceUrl;
  }


  public void setBackgroundSourceUrl(String backgroundSourceUrl) {
    
    
    
    this.backgroundSourceUrl = backgroundSourceUrl;
  }


  public VideosCreateVideoFromReplicaAndScriptRequest backgroundUrl(String backgroundUrl) {
    
    
    
    
    this.backgroundUrl = backgroundUrl;
    return this;
  }

   /**
   * A link to a website. This will be used as the background for the video. The website must be publicly accessible and properly formed.
   * @return backgroundUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A link to a website. This will be used as the background for the video. The website must be publicly accessible and properly formed.")

  public String getBackgroundUrl() {
    return backgroundUrl;
  }


  public void setBackgroundUrl(String backgroundUrl) {
    
    
    
    this.backgroundUrl = backgroundUrl;
  }


  public VideosCreateVideoFromReplicaAndScriptRequest replicaId(String replicaId) {
    
    
    
    
    this.replicaId = replicaId;
    return this;
  }

   /**
   * A unique identifier for the replica that will be used to generate the video.
   * @return replicaId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "r783537ef5", required = true, value = "A unique identifier for the replica that will be used to generate the video.")

  public String getReplicaId() {
    return replicaId;
  }


  public void setReplicaId(String replicaId) {
    
    
    
    this.replicaId = replicaId;
  }


  public VideosCreateVideoFromReplicaAndScriptRequest script(String script) {
    
    
    
    
    this.script = script;
    return this;
  }

   /**
   * A script to be used for the video.
   * @return script
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Hello from Tavus! Enjoy your new replica", required = true, value = "A script to be used for the video.")

  public String getScript() {
    return script;
  }


  public void setScript(String script) {
    
    
    
    this.script = script;
  }


  public VideosCreateVideoFromReplicaAndScriptRequest videoName(String videoName) {
    
    
    
    
    this.videoName = videoName;
    return this;
  }

   /**
   * A name for the video.
   * @return videoName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "My First Video", value = "A name for the video.")

  public String getVideoName() {
    return videoName;
  }


  public void setVideoName(String videoName) {
    
    
    
    this.videoName = videoName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the VideosCreateVideoFromReplicaAndScriptRequest instance itself
   */
  public VideosCreateVideoFromReplicaAndScriptRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideosCreateVideoFromReplicaAndScriptRequest videosCreateVideoFromReplicaAndScriptRequest = (VideosCreateVideoFromReplicaAndScriptRequest) o;
    return Objects.equals(this.backgroundSourceUrl, videosCreateVideoFromReplicaAndScriptRequest.backgroundSourceUrl) &&
        Objects.equals(this.backgroundUrl, videosCreateVideoFromReplicaAndScriptRequest.backgroundUrl) &&
        Objects.equals(this.replicaId, videosCreateVideoFromReplicaAndScriptRequest.replicaId) &&
        Objects.equals(this.script, videosCreateVideoFromReplicaAndScriptRequest.script) &&
        Objects.equals(this.videoName, videosCreateVideoFromReplicaAndScriptRequest.videoName)&&
        Objects.equals(this.additionalProperties, videosCreateVideoFromReplicaAndScriptRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backgroundSourceUrl, backgroundUrl, replicaId, script, videoName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideosCreateVideoFromReplicaAndScriptRequest {\n");
    sb.append("    backgroundSourceUrl: ").append(toIndentedString(backgroundSourceUrl)).append("\n");
    sb.append("    backgroundUrl: ").append(toIndentedString(backgroundUrl)).append("\n");
    sb.append("    replicaId: ").append(toIndentedString(replicaId)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    videoName: ").append(toIndentedString(videoName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("background_source_url");
    openapiFields.add("background_url");
    openapiFields.add("replica_id");
    openapiFields.add("script");
    openapiFields.add("video_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("replica_id");
    openapiRequiredFields.add("script");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VideosCreateVideoFromReplicaAndScriptRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!VideosCreateVideoFromReplicaAndScriptRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VideosCreateVideoFromReplicaAndScriptRequest is not found in the empty JSON string", VideosCreateVideoFromReplicaAndScriptRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VideosCreateVideoFromReplicaAndScriptRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("background_source_url") != null && !jsonObj.get("background_source_url").isJsonNull()) && !jsonObj.get("background_source_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `background_source_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("background_source_url").toString()));
      }
      if ((jsonObj.get("background_url") != null && !jsonObj.get("background_url").isJsonNull()) && !jsonObj.get("background_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `background_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("background_url").toString()));
      }
      if (!jsonObj.get("replica_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `replica_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replica_id").toString()));
      }
      if (!jsonObj.get("script").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `script` to be a primitive type in the JSON string but got `%s`", jsonObj.get("script").toString()));
      }
      if ((jsonObj.get("video_name") != null && !jsonObj.get("video_name").isJsonNull()) && !jsonObj.get("video_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `video_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("video_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VideosCreateVideoFromReplicaAndScriptRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VideosCreateVideoFromReplicaAndScriptRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VideosCreateVideoFromReplicaAndScriptRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VideosCreateVideoFromReplicaAndScriptRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<VideosCreateVideoFromReplicaAndScriptRequest>() {
           @Override
           public void write(JsonWriter out, VideosCreateVideoFromReplicaAndScriptRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public VideosCreateVideoFromReplicaAndScriptRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             VideosCreateVideoFromReplicaAndScriptRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VideosCreateVideoFromReplicaAndScriptRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VideosCreateVideoFromReplicaAndScriptRequest
  * @throws IOException if the JSON string is invalid with respect to VideosCreateVideoFromReplicaAndScriptRequest
  */
  public static VideosCreateVideoFromReplicaAndScriptRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VideosCreateVideoFromReplicaAndScriptRequest.class);
  }

 /**
  * Convert an instance of VideosCreateVideoFromReplicaAndScriptRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

