/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ReplicasCreateNewReplicaRequest;
import com.konfigthis.client.model.ReplicasCreateNewReplicaResponse;
import com.konfigthis.client.model.ReplicasGetReplicaByIdResponse;
import com.konfigthis.client.model.ReplicasListResponse;
import com.konfigthis.client.model.ReplicasRenameReplicaByIdRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReplicasApi
 */
@Disabled
public class ReplicasApiTest {

    private static ReplicasApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ReplicasApi(apiClient);
    }

    /**
     * Create Replica
     *
     * This endpoint creates a new Replica that can be used to generate personalized videos.   The only required body parameter is &#x60;train_video_url&#x60;. This url must be a download link such as a presigned S3 url. Please ensure you pass in a video that meets the [requirements](https://docs.tavusapi.com/api-reference) for training.  Replica training will fail without the following consent statement being present at the beginning of the video: &gt; I, [FULL NAME], am currently speaking and consent Tavus to create an AI clone of me by using the audio and video samples I provide. I understand that this AI clone can be used to create videos that look and sound like me.  Learn more about the consent statement [here](https://docs.tavusapi.com/api-reference).  Learn more about training a personal Replica [here](https://docs.tavusapi.com/api-reference). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewReplicaTest() throws ApiException {
        String trainVideoUrl = null;
        String callbackUrl = null;
        String replicaName = null;
        ReplicasCreateNewReplicaResponse response = api.createNewReplica(trainVideoUrl)
                .callbackUrl(callbackUrl)
                .replicaName(replicaName)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete Replica
     *
     * This endpoint deletes a single Replica by its unique identifier. Once deleted, this Replica can not be used to generate videos. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByReplicaIdTest() throws ApiException {
        String replicaId = null;
        api.deleteByReplicaId(replicaId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Replica
     *
     * This endpoint returns a single Replica by its unique identifier.   Included in the response body is a &#x60;training_progress&#x60; string that represents the progress of the Replica training. If there are any errors during training, the &#x60;status&#x60; will be &#x60;error&#x60; and the &#x60;error_message&#x60; will be populated. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getReplicaByIdTest() throws ApiException {
        String replicaId = null;
        ReplicasGetReplicaByIdResponse response = api.getReplicaById(replicaId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Replicas
     *
     * This endpoint returns a list of all replicas that have been created by the API Key in use. In the response, a root level &#x60;data&#x60; key will contain the list of Replicas. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        ReplicasListResponse response = api.list()
                .execute();
        // TODO: test validations
    }

    /**
     * Rename Replica
     *
     * This endpoint renames a single Replica by its unique identifier.  
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renameReplicaByIdTest() throws ApiException {
        String replicaName = null;
        String replicaId = null;
        api.renameReplicaById(replicaName, replicaId)
                .execute();
        // TODO: test validations
    }

}
