/*
 * Tavus Developer API Collection
 * We're an AI video research company making personalized video possible at scale. Generate videos of yourself, and never record again! Available via web app & developer APIs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.VideosCreateVideoFromReplicaAndScriptRequest;
import com.konfigthis.client.model.VideosCreateVideoFromReplicaAndScriptResponse;
import com.konfigthis.client.model.VideosGetAllResponse;
import com.konfigthis.client.model.VideosGetByVideoIdResponse;
import com.konfigthis.client.model.VideosUpdateNameRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VideosApi
 */
@Disabled
public class VideosApiTest {

    private static VideosApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new VideosApi(apiClient);
    }

    /**
     * Generate Video
     *
     * This endpoint generates a new video using a Replica and a script.   The only required body parameters are &#x60;replica_id&#x60; and &#x60;script&#x60;. The &#x60;replica_id&#x60; is a unique identifier for the Replica that will be used to generate the video. The &#x60;script&#x60; is the text that will be spoken by the Replica in the video.  If a &#x60;background_url&#x60; is provided, Tavus will record a video of the website and use it as the background for the video. If a &#x60;background_source_url&#x60; is provided, where the URL points to a download link such as a presigned S3 URL, Tavus will use the video as the background for the video. If neither are provided, the video will consist of a full screen Replica.  To learn more about generating videos with Replicas, see [here](https://docs.tavusapi.com/api-reference).  To learn more about writing an effective script for your video, see [Scripting prompting](https://docs.tavusapi.com/api-reference). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVideoFromReplicaAndScriptTest() throws ApiException {
        String replicaId = null;
        String script = null;
        String backgroundSourceUrl = null;
        String backgroundUrl = null;
        String videoName = null;
        VideosCreateVideoFromReplicaAndScriptResponse response = api.createVideoFromReplicaAndScript(replicaId, script)
                .backgroundSourceUrl(backgroundSourceUrl)
                .backgroundUrl(backgroundUrl)
                .videoName(videoName)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete Video
     *
     * This endpoint deletes a single video by its unique identifier. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByVideoIdTest() throws ApiException {
        String videoId = null;
        api.deleteByVideoId(videoId)
                .execute();
        // TODO: test validations
    }

    /**
     * List Videos
     *
     * This endpoint returns a list of all videos that have been generated by the API Key in use.  
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        VideosGetAllResponse response = api.getAll()
                .execute();
        // TODO: test validations
    }

    /**
     * Get Video
     *
     * This endpoint returns a single video by its unique identifier.   The response body will contain a &#x60;status&#x60; string that represents the status of the video. If the video is ready, the response body will also contain a &#x60;download_url&#x60;, &#x60;stream_url&#x60;, and &#x60;hosted_url&#x60; that can be used to download, stream, and view the video respectively. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByVideoIdTest() throws ApiException {
        String videoId = null;
        VideosGetByVideoIdResponse response = api.getByVideoId(videoId)
                .execute();
        // TODO: test validations
    }

    /**
     * Rename Video
     *
     * This endpoint renames a single video by its unique identifier. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateNameTest() throws ApiException {
        String videoName = null;
        String videoId = null;
        api.updateName(videoName, videoId)
                .execute();
        // TODO: test validations
    }

}
